-- Ninauu master gear catalog seed
-- Run catalog_migration.sql first, then this file
-- Truncate existing catalog data before re-seeding:
-- TRUNCATE TABLE gear_catalog;

insert into gear_catalog (name, brand, weight_g, category, is_verified) values

-- ───────────── Tent ─────────────
('Duplex Tent', 'Zpacks', 510, 'Tent', true),
('Plexamid Tent', 'Zpacks', 368, 'Tent', true),
('Arc Haul Scout Tent', 'Zpacks', 595, 'Tent', true),
('3400 Dirigo 2', 'Hyperlite Mountain Gear', 652, 'Tent', true),
('Lunar Solo', 'Six Moon Designs', 595, 'Tent', true),
('Copper Spur HV UL2', 'Big Agnes', 1080, 'Tent', true),
('Hornet Elite OSMO 2P', 'NEMO', 794, 'Tent', true),
('Notch Li', 'Tarptent', 537, 'Tent', true),
('Carbon Reflex 1', 'MSR', 680, 'Tent', true),
('Hilight 3 Season Tent', 'Black Diamond', 1090, 'Tent', true),
('Cloud-Up 2', 'Naturehike', 1350, 'Tent', true),
('TREK RAIZ 0', 'ARAI TENT', 1470, 'Tent', true),
('Akto', 'Hilleberg', 1700, 'Tent', true),
('Nallo 2 GT', 'Hilleberg', 2000, 'Tent', true),
('Telos TR2', 'Sea to Summit', 1090, 'Tent', true),
('X-Mid 2P', 'Durston Gear', 595, 'Tent', true),
('Aeon Li', 'Terra Nova', 480, 'Tent', true),
('Moment DW', 'MSR', 1130, 'Tent', true),
('Mutha Hubba NX 3P', 'MSR', 1700, 'Tent', true),

-- ───────────── Sleeping bag ─────────────
('Revelation Quilt 20°F', 'Enlightened Equipment', 398, 'Sleeping bag', true),
('Flex 22 Quilt', 'Katabatic Gear', 369, 'Sleeping bag', true),
('UltraLite 20°F', 'Western Mountaineering', 680, 'Sleeping bag', true),
('Swallow YF 20', 'Feathered Friends', 510, 'Sleeping bag', true),
('Spark SP III', 'Sea to Summit', 500, 'Sleeping bag', true),
('U.L. Super Spiral Down Hugger #3', 'mont-bell', 530, 'Sleeping bag', true),
('Aurora 800DX 3-Ten', 'NANGA', 1350, 'Sleeping bag', true),
('X-Lite 300', 'Cumulus', 465, 'Sleeping bag', true),
('Panyam 450', 'Cumulus', 620, 'Sleeping bag', true),
('Micra IV', 'Western Mountaineering', 340, 'Sleeping bag', true),
('Neutrino 400', 'Rab', 727, 'Sleeping bag', true),
('Ascent 700', 'PHD', 590, 'Sleeping bag', true),
('Mystic 0°', 'NEMO', 1000, 'Sleeping bag', true),
('Phantom 15°F', 'Big Agnes', 595, 'Sleeping bag', true),
('Solo Quilt 20°F', 'Zpacks', 312, 'Sleeping bag', true),
('Lynx Pass 30°F', 'Big Agnes', 595, 'Sleeping bag', true),

-- ───────────── Sleeping mat ─────────────
('NeoAir UberLite', 'Therm-a-Rest', 250, 'Sleeping mat', true),
('NeoAir XLite NXT', 'Therm-a-Rest', 354, 'Sleeping mat', true),
('Z Lite Sol', 'Therm-a-Rest', 410, 'Sleeping mat', true),
('ProLite Plus', 'Therm-a-Rest', 510, 'Sleeping mat', true),
('Tensor Ultralight', 'NEMO', 350, 'Sleeping mat', true),
('Tensor Extreme Conditions', 'NEMO', 710, 'Sleeping mat', true),
('Ether Light XT Insulated', 'Sea to Summit', 599, 'Sleeping mat', true),
('Ultra 1R', 'Exped', 275, 'Sleeping mat', true),
('DownMat XP 9', 'Exped', 1010, 'Sleeping mat', true),
('ThinLight 1/8"', 'Gossamer Gear', 99, 'Sleeping mat', true),
('Static V2', 'Klymit', 510, 'Sleeping mat', true),
('Insulated Static V', 'Klymit', 680, 'Sleeping mat', true),
('Q-Core SLX', 'Big Agnes', 480, 'Sleeping mat', true),

-- ───────────── Backpack ─────────────
('Arc Haul Ultra 60L', 'Zpacks', 504, 'Backpack', true),
('Arc Blast 55L', 'Zpacks', 481, 'Backpack', true),
('Nero Ultra 38L', 'Zpacks', 417, 'Backpack', true),
('3400 Southwest', 'Hyperlite Mountain Gear', 737, 'Backpack', true),
('2400 Southwest', 'Hyperlite Mountain Gear', 709, 'Backpack', true),
('Mariposa 60L', 'Gossamer Gear', 596, 'Backpack', true),
('Gorilla 40L', 'Gossamer Gear', 510, 'Backpack', true),
('Circuit 68L', 'ULA Equipment', 680, 'Backpack', true),
('Crown2 60L', 'Granite Gear', 1020, 'Backpack', true),
('Exos 58', 'Osprey', 1190, 'Backpack', true),
('Levity 60', 'Gregory', 1010, 'Backpack', true),
('Fusion 55', 'Six Moon Designs', 680, 'Backpack', true),
('Light Trail Pack 30L', 'mont-bell', 620, 'Backpack', true),
('BAEKDU 2 40L+15L', 'Cayl', 933, 'Backpack', true),
('Muon 40', 'Atom Packs', 430, 'Backpack', true),

-- ───────────── Apparel ─────────────
('Houdini Jacket', 'Patagonia', 110, 'Apparel', true),
('Atom SL Hoody', 'Arc''teryx', 210, 'Apparel', true),
('Nano Puff Jacket', 'Patagonia', 311, 'Apparel', true),
('Challenger Wind Shell', 'Zpacks', 82, 'Apparel', true),
('Vertice Rain Jacket', 'Zpacks', 163, 'Apparel', true),
('Helium Rain Jacket', 'Outdoor Research', 198, 'Apparel', true),
('Microlight Alpine Jacket', 'Rab', 290, 'Apparel', true),
('Versalite Jacket', 'mont-bell', 120, 'Apparel', true),
('Plasma 1000 Down Jacket', 'mont-bell', 135, 'Apparel', true),
('Torrid Apex Jacket', 'Enlightened Equipment', 260, 'Apparel', true),
('Coefficient Fleece Hoody', 'Black Diamond', 302, 'Apparel', true),
('Ether Hood', 'Montane', 310, 'Apparel', true),
('Vital Light Jacket', 'Rab', 148, 'Apparel', true),
('Ghostwhisperer/2 Hoodie', 'Mountain Hardwear', 199, 'Apparel', true),
('Ventia FL Jacket', 'Arc''teryx', 310, 'Apparel', true),

-- ───────────── Footwear ─────────────
('Lone Peak 8', 'Altra', 540, 'Footwear', true),
('Olympus 5', 'Altra', 580, 'Footwear', true),
('Speedgoat 6', 'Hoka', 610, 'Footwear', true),
('Speedcross 6', 'Salomon', 640, 'Footwear', true),
('Sense Ride 5', 'Salomon', 560, 'Footwear', true),
('TrailFly Ultra G 300 Max', 'Inov-8', 500, 'Footwear', true),
('Trailfly G 270', 'Inov-8', 540, 'Footwear', true),
('Ultraventure 3', 'Topo Athletic', 560, 'Footwear', true),
('Cascadia 16', 'Brooks', 600, 'Footwear', true),
('Wildfire 2 GTX', 'La Sportiva', 760, 'Footwear', true),
('Trail 2650 GTX', 'Danner', 680, 'Footwear', true),
('Renegade GTX Mid', 'Lowa', 1080, 'Footwear', true),

-- ───────────── Cook ─────────────
('PocketRocket 2', 'MSR', 73, 'Cook', true),
('PocketRocket Deluxe', 'MSR', 119, 'Cook', true),
('WindMaster Stove', 'Soto', 67, 'Cook', true),
('Amicus Stove', 'Soto', 75, 'Cook', true),
('3000T Ultralight Stove', 'BRS', 25, 'Cook', true),
('LiteMax Stove', 'Snow Peak', 56, 'Cook', true),
('GigaPower 2.0 Stove', 'Snow Peak', 69, 'Cook', true),
('Trek 1400 Ti Cook Set', 'Snow Peak', 285, 'Cook', true),
('Flash Cooking System', 'Jetboil', 371, 'Cook', true),
('MicroMo Cooking System', 'Jetboil', 328, 'Cook', true),
('Titanium 750ml Pot', 'Toaks', 99, 'Cook', true),
('Titanium Long Handle Spoon', 'Toaks', 15, 'Cook', true),
('0.9L Titanium Non-Stick Pot', 'Evernew', 92, 'Cook', true),
('Ultralight Esbit Folding Stove', 'Esbit', 25, 'Cook', true),
('X-Pot 1.4L', 'Sea to Summit', 195, 'Cook', true),
('Titanium Spork', 'Light My Fire', 12, 'Cook', true),

-- ───────────── Water ─────────────
('Squeeze Filter', 'Sawyer', 85, 'Water', true),
('Mini Filter', 'Sawyer', 57, 'Water', true),
('BeFree Filter 1L', 'Katadyn', 60, 'Water', true),
('Trail Shot', 'MSR', 140, 'Water', true),
('Steripen Adventurer Opti', 'SteriPen', 90, 'Water', true),
('Platy 2L Soft Bottle', 'Platypus', 36, 'Water', true),
('Seeker 2L', 'Hydrapak', 62, 'Water', true),
('Stow 1L', 'Hydrapak', 32, 'Water', true),
('Vecto 3L Bag', 'CNOC Outdoors', 47, 'Water', true),
('Water Purification Tablets x50', 'Aquatabs', 25, 'Water', true),
('Logo Bottle 500ml', 'and wander', 110, 'Water', true),
('Collapsible 1L Soft Canteen', 'Sea to Summit', 38, 'Water', true),

-- ───────────── Electronics ─────────────
('inReach Mini 2', 'Garmin', 100, 'Electronics', true),
('inReach Messenger', 'Garmin', 116, 'Electronics', true),
('Forerunner 255', 'Garmin', 49, 'Electronics', true),
('Fenix 7S Solar', 'Garmin', 63, 'Electronics', true),
('Spot 400-R Headlamp', 'Black Diamond', 95, 'Electronics', true),
('Revolt 1500 Headlamp', 'Black Diamond', 98, 'Electronics', true),
('BINDI Headlamp', 'Petzl', 35, 'Electronics', true),
('ACTIK CORE Headlamp', 'Petzl', 100, 'Electronics', true),
('NU25 Headlamp', 'Nitecore', 52, 'Electronics', true),
('NB10000 Power Bank', 'Nitecore', 150, 'Electronics', true),
('PowerCore 10000', 'Anker', 180, 'Electronics', true),
('Nano Power Bank 30W', 'Anker', 96, 'Electronics', true),

-- ───────────── Accessories ─────────────
('Distance Carbon Z Trekking Poles', 'Black Diamond', 440, 'Accessories', true),
('Ultra Distance Carbon Z', 'Black Diamond', 382, 'Accessories', true),
('Micro Vario Carbon Poles', 'Leki', 490, 'Accessories', true),
('FKT Pole', 'Gossamer Gear', 368, 'Accessories', true),
('Lightrek Trekking Umbrella', 'Gossamer Gear', 164, 'Accessories', true),
('Ultra-Sil Dry Bag 8L', 'Sea to Summit', 39, 'Accessories', true),
('Ultra-Sil Dry Bag 20L', 'Sea to Summit', 58, 'Accessories', true),
('DCF Dry Bag 20L', 'Zpacks', 56, 'Accessories', true),
('DCF Rain Kilt', 'Zpacks', 52, 'Accessories', true),
('Groundhog Tent Stake', 'MSR', 9, 'Accessories', true),
('Groundhog Tent Stake Mini', 'MSR', 6, 'Accessories', true),
('V-Stake', 'Vargo', 8, 'Accessories', true),
('Titanium Shepherd Hook Stake', 'Toaks', 7, 'Accessories', true),
('Buff UV Multifunctional', 'Buff', 36, 'Accessories', true),
('Sun Runner Cap', 'Outdoor Research', 95, 'Accessories', true),
('Airlite Towel S', 'Sea to Summit', 30, 'Accessories', true),
('Drylite Towel M', 'Sea to Summit', 76, 'Accessories', true),
('Fold-A-Cup', 'Wildo', 25, 'Accessories', true),
('First Aid Kit Ultralight', 'Adventure Medical Kits', 130, 'Accessories', true),

-- ───────────── Chair ─────────────
('Chair Zero', 'Helinox', 510, 'Chair', true),
('Chair One', 'Helinox', 960, 'Chair', true),
('Chair One High Back', 'Helinox', 1300, 'Chair', true),
('Sunset Chair', 'Helinox', 890, 'Chair', true),
('Swivel Chair Zero', 'Helinox', 570, 'Chair', true),
('Hex 2.0 Original Chair', 'Crazy Creek', 390, 'Chair', true),
('Air Chair 2.0', 'Crazy Creek', 340, 'Chair', true),

-- ───────────── Pillow ─────────────
('Fillo Elite Pillow', 'NEMO', 58, 'Pillow', true),
('Aeros Premium Pillow', 'Sea to Summit', 67, 'Pillow', true),
('Air Head Pillow', 'Therm-a-Rest', 66, 'Pillow', true),
('Compressible Pillow S', 'Therm-a-Rest', 113, 'Pillow', true),
('ALUFT 2.0 Pillow', 'Trekology', 59, 'Pillow', true),
('Pillow X', 'Klymit', 68, 'Pillow', true),
('Ultralight Pillow', 'Nemo', 48, 'Pillow', true),

-- ───────────── Others ─────────────
('Polycro Ground Cloth', 'Gossamer Gear', 43, 'Others', true),
('Tyvek Ground Sheet', 'HIKER WORKSHOP', 120, 'Others', true),
('TREK RAIZ0 Under Sheet', 'ARAI TENT', 150, 'Others', true),
('Bivy Sack Ultralight', 'Outdoor Research', 255, 'Others', true),
('Emergency Bivy', 'SOL', 113, 'Others', true),
('Bear Canister BV500', 'BearVault', 920, 'Others', true),
('Ursack Major XL', 'Ursack', 213, 'Others', true),
('Ditty Bag S', 'Sea to Summit', 27, 'Others', true),
('Ultralight Stuff Sack 10L', 'Sea to Summit', 23, 'Others', true),
('Nite Ize Figure 9 Carabiner', 'Nite Ize', 20, 'Others', true),
('Micro Cord 100ft', 'Atwood Rope', 64, 'Others', true);
